services:
  database:
    container_name: database-container
    image: 'postgres:17'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data/'
    env_file: .env
    networks:
      - app_network

  backend:
    container_name: back-container
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
